S01US01 - "En tant qu'utilisateur, je peux accéder à une barre de navigation et à footer"
a-deux-pas/front-a-deux-pas pull request #12
Opened 2024-05-11 15:23 UTC by leahad

- Created default-home component which includes the header and the categories
- Created navbar and a footer components in `shared > components`
- Created specific style for mobile and desktop versions
- Added navigation routes

2024-05-11 16:17 UTC, Erikaike requested changes

2024-05-11 16:17 UTC, Erikaike commented on src/app/shared/components/footer/footer.component.html
> +          <img src="/assets/icons/social-networks/facebook.webp" alt="Icône facebook" class="social-networks-icon"/>
dans le header.html , dans ton alt ,"icône"  avait un i minuscule alors qu'il est en majuscule ici

2024-05-11 16:17 UTC, Erikaike commented on src/app/shared/components/footer/footer.component.html
> +            class="social-networks-icon"
les attributs de ta balise img sont sur plusieurs lignes ici alors qu'ils sont sur une ligne sur la l.20

2024-05-11 16:17 UTC, Erikaike commented on src/app/shared/components/navbar/navbar.component.scss
> +    padding:0;
espace apres ":"

2024-05-11 17:37 UTC, leahad commented on src/app/routes/home/default-home/components/header/header.component.html
> +        </button>
ici le user n'est pas connecté, lorsqu'il clique sur le bouton vendre il doit être redirigé vers le pop up de connection d'où mon commentaire

2024-05-11 21:01 UTC, Erikaike commented on src/app/shared/components/navbar/navbar.component.html
> +        <a routerLink="" class="account-menu-item" id="logout" (click)="toggleAccountMenuState()">Se déconnecter</a>
est ce que routerLink=""  redirige quelque part ?

2024-05-11 21:09 UTC, Erikaike commented on src/app/shared/components/tabs-account/tabs-account.component.html
> +        <a ngbNavLink [routerLink]="['/compte', route.path]" [class.custom-active-tab]="active === route.path">{{ route.title }}</a>
Attention
il y a des moment où tu écris routerLink entre [...] et d'autres pas.
De plus, ici le lien qui suit est en [..]  alors qu'à d'autres endroits (ex: l.66 du navbar.html) ce n'est pas le cas

2024-05-11 21:11 UTC, Erikaike commented on src/app/shared/components/tabs-account/tabs-account.component.html
> +        <a ngbNavLink [routerLink]="['/compte', route.path]" [class.custom-active-tab]="active === route.path">{{ route.title }}</a>
De plus ici, tu separes ta partie variables du reste avec une ',' alors que dans ton utilisation du routerLInk dans le navBar.html tu le separes avec un '+'

2024-05-11 21:13 UTC, Erikaike commented on src/style/styles.scss
> +    background-color:$tertiary;
espace avant $

2024-05-12 07:06 UTC, leahad commented on src/app/shared/components/navbar/navbar.component.html
> +        <a routerLink="" class="navbar-icon">
bien vu ! j'avais oublié qu'il s'agissait de la page d'accueil lorsque l'on était connecté du coup j'ai créé le composant et la route logged-in-home

2024-05-12 07:33 UTC, leahad commented on src/app/shared/components/tabs-account/tabs-account.component.html
> +        <a ngbNavLink [routerLink]="['/compte', route.path]" [class.custom-active-tab]="active === route.path">{{ route.title }}</a>
Si je change ces éléments, les tabs ne fonctionnent plus :
**Concernant `[routerLink]` :**
Les crochets `[...]` permettent d'indiquer à Angular que la valeur de routerLink est une expression dynamique, amenée à changer ce qui est le cas dans le menu de la navbar et ici pour les tabs.
**Concernant `"['/compte', route.path]"` :**
Je ne sais pas pourquoi mais si j'utilise le même format que ce que j'ai fait pour la navbar cela ne fonctionne pas, c'est peut-être dû au fait qu'il s'agit ici d'un composant NgBootstrap. Selon ChatGPT, La différence principale entre les deux est que `[routerLink]="'compte/' + route.path"` crée une URL relative à l'URL actuelle, tandis que `['/compte', route.path]` crée une URL absolue.

2024-05-12 17:55 UTC, Erikaike requested changes

2024-05-12 17:55 UTC, Erikaike commented on src/app/shared/components/navbar/navbar.component.html
> +      <img class="mobile-footsteps"src="assets/icons/mobile-footsteps.webp" alt="icône de traces de pas"/>
espace entre class="mobile-footsteps" et src="assets/icons/mobile-footsteps.webp"

2024-05-12 17:55 UTC, Erikaike commented on src/app/routes/home/default-home/components/header/header.component.html
> +            <button type="submit" class="btn-connection mb-4">se connecter</button>
"se connecter" est en écrit avec s minuscule sur cette ligne et sur la ligne 30 alors que "Se déconnecter" est ecrit avec S maj sur le navbar.html

2024-05-12 17:55 UTC, Erikaike commented on src/app/routes/home/default-home/components/header/header.component.scss
> +}
les 3 lignes ne pourrait elles pas être remplacées par "margin: 0 !important;" ?

2024-05-12 18:14 UTC, leahad commented on src/app/routes/home/default-home/components/header/header.component.html
> +            <button type="submit" class="btn-connection mb-4">se connecter</button>
![image](https://github.com/a-deux-pas/front-a-deux-pas/assets/120429388/9080aacf-83e8-4ff8-9a18-581bccc6f1a9)
oui car il s'agit du menu déroulant dans lequel tout est en majuscule

2024-05-13 08:54 UTC, Erikaike requested changes

2024-05-13 08:54 UTC, Erikaike commented on src/app/routes/home/default-home/components/header/header.component.scss
> +  font-size: 17px;
peut etre mettre en rem par soucis de cohérence avec le reste

2024-05-13 08:54 UTC, Erikaike commented on src/app/routes/home/default-home/components/header/header.component.scss
> +    font-size: 18px;
peut etre mettre en rem par soucis de cohérence avec le reste

2024-05-13 08:54 UTC, Erikaike commented on src/app/shared/components/navbar/navbar.component.scss
> +  font-size: 20px;
peut etre mettre en rem par soucis de cohérence avec le reste

2024-05-13 08:54 UTC, Erikaike commented on src/app/shared/components/navbar/navbar.component.scss
> +    font-size: 16px;
peut etre mettre en rem par soucis de cohérence avec le reste

2024-05-13 08:54 UTC, Erikaike commented on src/style/styles.scss
> +  font-size: 12px;
peut etre mettre en rem par soucis de cohérence avec le reste

2024-05-13 13:46 UTC, Erikaike requested changes

2024-05-13 13:46 UTC, Erikaike commented on src/app/routes/home/default-home/default-home.component.scss
> +    padding-right: 0;
padding : 0;

2024-05-13 13:46 UTC, Erikaike commented on src/app/routes/home/logged-in-home/logged-in-home.component.ts
> +  imports: [],
ligne à supprimer ?

2024-05-13 13:46 UTC, Erikaike commented on src/app/shared/components/navbar/navbar.component.scss
> +  top:0;
un espace apres le ": "

2024-05-13 13:46 UTC, Erikaike commented on src/app/shared/components/navbar/navbar.component.scss
> +  cursor: pointer;
cette propriété n'est elle pas déjà dans le style.scss ?

2024-05-13 13:46 UTC, Erikaike commented on src/app/shared/components/navbar/navbar.component.scss
> +@media (min-width: 1941px) {
remove .fix

2024-05-13 13:46 UTC, Erikaike commented on src/app/shared/components/navbar/search-bar/search-bar.component.ts
> +  imports: [],
ligne à supprimer ?

2024-05-13 13:46 UTC, Erikaike commented on src/style/styles.scss
>    margin-right: 2vh !important;
possible de factoriser les margin ?

2024-05-13 13:46 UTC, Erikaike commented on src/style/styles.scss
> +  background-color:$tertiary;
un espace apres ":"

2024-05-13 13:46 UTC, Erikaike commented on src/style/styles.scss
> +    content: '';
utile ?

2024-05-13 13:46 UTC, Erikaike commented on src/style/styles.scss
> +    border-top-right-radius: 542px 18px;
factoriser dans le &::before

2024-05-13 13:46 UTC, Erikaike commented on src/style/styles.scss
> +    border-top-left-radius: 542px 18px;
factoriser dans le &::before

2024-05-13 13:46 UTC, Erikaike commented on src/style/styles.scss
> +    width: 50%;
factoriser dans le &::before

2024-05-13 13:46 UTC, Erikaike commented on src/style/styles.scss
> +    width: 50%;
factoriser dans le &::before

2024-05-13 13:46 UTC, Erikaike commented on src/style/styles.scss
>    box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
factorisable en 2 valeurs ?

2024-05-13 14:31 UTC, leahad commented on src/app/shared/components/navbar/navbar.component.scss
> +  cursor: pointer;
et ba je te confirme que cela ne sert à rien... on se demande bien qui a pu mettre ça là 😄

2024-05-13 14:48 UTC, leahad commented on src/style/styles.scss
> +    border-top-right-radius: 542px 18px;
en fait je me suis rendue compte que ce n'est pas les mêmes radius, celui là concerne la partie droite et l'autre la partie gauche donc pas possible de refactoriser

2024-05-13 14:52 UTC, leahad commented on src/style/styles.scss
>    box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
c'est toi qui codé ce bouton 😄

2024-05-14 08:35 UTC, Erikaike requested changes

2024-05-14 08:35 UTC, Erikaike commented on src/app/routes/home/default-home/components/header/header.component.scss
> +  margin-top: 32px;
peut être factorisé par margin: 32px auto 0;

2024-05-14 08:35 UTC, Erikaike commented on src/app/shared/components/navbar/navbar.component.scss
> +  top: 0;
Les lignes 
  position: absolute;
  background-color: $tertiary;
  width: 100%;
  top: 0;
  peuvent être remplacées par @extend .mobile-top-nav-background;

2024-05-14 08:35 UTC, Erikaike commented on src/app/shared/components/navbar/navbar.component.scss
> +  overflow-y: auto;
je pense que les lignes
 background-color: $tertiary;
  width: 100%;
  top: 0;
  peuvent être remplacées par  @extend .mobile-top-nav-background;

2024-05-14 08:35 UTC, Erikaike commented on src/app/shared/components/navbar/navbar.component.scss
> +  align-items: center;
les lignes
  display: flex;
  flex-direction: column;
  align-items: center;
  
  peuvent être remplacées par @extend.desktop-navbar-icon

2024-05-14 08:35 UTC, Erikaike commented on src/app/shared/components/navbar/navbar.component.scss
> +  background-color: $tertiary;
les lignes
display: flex;
flex-direction: column;
align-items: center;

peuvent être remplacées par @extend.desktop-navbar-icon
(ce selecteur sera peut-être à placé apres .desktop-navbar-icon pour que ca marche je suis pas sûre)

2024-05-14 08:43 UTC, leahad commented on src/app/routes/home/default-home/components/header/header.component.scss
> +  margin-top: 32px;
J'ai testé est ça fait péter la mise en page...

2024-05-14 08:49 UTC, leahad commented on src/app/shared/components/navbar/navbar.component.scss
> +  top: 0;
Je connaissais pas !! c'est trop bien :)

2024-05-14 08:53 UTC, leahad commented on src/app/shared/components/navbar/navbar.component.scss
> +  overflow-y: auto;
ici cela ne fonctionne pas, ça annule la position fixed

2024-05-14 09:57 UTC, Erikaike approved these changes

2024-05-14 09:57 UTC, merged