S01us02 new
a-deux-pas/front-a-deux-pas pull request #14
Opened 2024-05-24 22:21 UTC by douniabed

2024-05-27 21:03 UTC, Erikaike requested changes

2024-05-27 21:03 UTC, Erikaike commented on src/app/shared/tests/e2e/create-ad.cy.ts
> +});
oublie pas de virer ce fichier de ta PR comme je t'ai envoyé ce sur quoi cliqué sur discord ;)

2024-05-27 21:03 UTC, Erikaike commented on src/style/style-guide/style-guide-routing.module.ts
> +export class StyleGuideRoutingModule { }
ca devait pas aussi être virer de ta PR ?

2024-05-27 21:03 UTC, Erikaike commented on src/style/style-guide/style-guide.component.html
> +</div>
ca devait pas aussi être virer de ta PR ?

2024-05-27 21:03 UTC, Erikaike commented on src/style/style-guide/style-guide.component.ts
> +}
ca devait pas aussi être virer de ta PR ?

2024-05-27 21:03 UTC, Erikaike commented on src/style/styles.scss
> +  .wave::after {
tu peux ajouter un saut de ligne au dessus

2024-05-27 21:03 UTC, Erikaike commented on src/style/styles.scss
> +    &.active {
tu pourrais supprimer les lignes 439 à 442 et juste mettre '&:hover' en plus vu qu'ils ont les mêmes propriétés

2024-05-27 21:20 UTC, douniabed commented on src/app/routes/login/login.component.html
> +        width="50px"
J'ai pas compris !

2024-05-27 21:21 UTC, douniabed commented on src/app/routes/login/login.component.html
> +          <div class="alert">
Pourquoi je dois faire ça  , alors que la classe alert de bootstrap fait tout le travail !

2024-05-27 21:24 UTC, douniabed commented on src/app/routes/login/login.component.html
> +          <div class="alert">
Oui c'est possible

2024-05-28 08:07 UTC, leahad commented on src/app/routes/home/default-home/components/header/header.component.ts
> +  showSuccessAlert: boolean = false;
Cela me fait penser qu'il ne me semble pas avoir vu l'alert connection success qui est censée apparaitre lorsqu'on se connecte ?

2024-05-28 11:42 UTC, douniabed commented on src/app/app-routing.module.ts
> +    canActivate: [authGuard],
SI, mais au début j'ai pas toutes les routes .

2024-05-28 15:28 UTC, Erikaike commented on src/app/routes/login/login.component.html
@douniabed  , je me permet de ré soulever ce qui a été dit par @leahad  , laisser le login ici irait à l'encontre du choix qu'on a fait pour notre architecture front donc je pense que ce serait pas mal de le bouger dans shared/ . Si je ne me trompe pas, ce serait juste une question de changement de chemin et d'import pour que tout soit cablé correctement apres son déplacement. Je sais que vu que tu y a passé du temps tu dois en avoir un peu marre mdr mais ce serait pas mal de le bouger maintenant que tu es sur cette US, plutôt que repousser ca à plus tard ou pire encore, que quelqu'un dont ce n'est pas la tâche doivent s'en charger.

Hesite pas si tu veux qu'on le fasse ensemble ;)

2024-05-29 20:25 UTC, douniabed commented on src/app/app-routing.module.ts
> +    canActivate: [authGuard],
il suffit juste de rajouter canActivate: [authGuard] sur les routes  qui nécessite que le user soit connecté

2024-05-31 23:20 UTC, douniabed commented on src/app/routes/login/login.component.scss
> +.modal-body .error-msg {
je l'ai supp

2024-05-31 23:20 UTC, douniabed commented on src/app/shared/services/auth.service.ts
> +        `http://localhost:8081/login`, // API endpoint for login
c'est fait

2024-06-01 09:34 UTC, Erikaike commented on src/app/app.component.html
>  <!-- TO DO : ajouter une condition pour afficher la navbar uniquement si l'user est connecté -->
du coup si c'est fait tu peux virer le commentaire et ajouté une ligne vide en fin de fichier 🥳

2024-06-01 09:34 UTC, Erikaike commented on src/style/styles.scss
> +.modal-header {
Et ajouter une ligne vide au dessus de .modal-header  😛

2024-06-01 09:42 UTC, douniabed commented on src/style/styles.scss
> +.modal-header {
Non , mais c'est abusé !! ça fait 3 mois que je fais et je refais  cette US et là tu me la blogue juste pour un espace . pourquoi en fait !!!!

2024-06-01 09:46 UTC, Erikaike commented on src/style/styles.scss
> +.modal-header {
parce que ca te prendrais un quart de seconde de le faire non ? 😉 (Tu vas pas me faire une Mircea pour ca non 😇)
Et puis parce que @leahad avait commenté pour que tu ajoutes une séparateur et c'était pas fait.
Maintenant prend en compte ce qu'il y a à prendre en compte ,je sais plus si ce fichier doit être dans ta PR ou non.

2024-06-01 13:41 UTC, BardanMircea commented on src/style/styles.scss
> +.modal-header {
@Erikaike , c'est quoi une Mircea?

2024-06-01 13:50 UTC, Erikaike commented on src/style/styles.scss
> +.modal-header {
Ben, si mes souvenirs sont bons, toi aussi tu avais été triggered par le fait que j'avais commenté ta PR sur le fait d'ajouter un espace (ou une virgule me souviens plus ) d'où la comparaison 😊

2024-06-01 19:49 UTC, leahad reviewed
Merci pour les modifications apportées !  Je t'ai fait 2 commentaires qui représentent des petites modifs si tu as le temps . Comme discuté ensemble ce matin, pour retirer les sens interdits des fichier suivants :  app.component.html et create-ad.cy.ts, il te suffit d'ajouter une ligne vide à la fin du fichier. Sinon c'est tout bon !

2024-06-01 19:49 UTC, leahad commented on src/app/routes/account/account-routing.module.ts
je crois que tu as laissé les virgules quand tu as enlevé les `guards` tout à l'heure, ligne 13, 18, 23 et 28. Si tu ne veux pas t'embêter, il te suffit de copier coller le fichier depuis la dev (sans oublier l'ajout de la ligne à la fin);

2024-06-01 19:49 UTC, leahad commented on src/app/routes/home/logged-in-home/logged-in-home.component.ts
> +  imports: [CommonModule],
Je vois que tu as ajouté le Common Module ici alors que tu n'as pas modifié le reste du composant, est-ce que c'est un oubli ? ou cela sert à quelque chose ?

2024-06-01 20:57 UTC, douniabed commented
J'ai dû commenter le test create-ad.cy car ça bloque la CI (Erika compte le modifié)

2024-06-02 18:47 UTC, leahad approved these changes

2024-06-02 18:53 UTC, Erikaike approved these changes

2024-06-02 18:53 UTC, merged